[package]
name = "skillet"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
#glium = "0.21.0"
glium_text = "*"
image = "0.24.3"
serde_json = "1.0.85"
vtkio = "0.6"

